
version: '3'

services:


    DC3N1:
        container_name: container_hdfs_stressTest_N1
        image: image_hdfs_release-2.9.0
        command: bash -c 'sleep 0 && /usr/bin/supervisord'
        networks:
            network_2.1.1_to_2.3.7_stressTest_dc1ring:
                ipv4_address:  252.18.1.2
        volumes:
            - /home/zhuqi/upgrade_test/submit/src/../tests/hive/stress/2.1.1_to_2.3.7/stressTest/persistent/data/n1data:/tmp
            - /home/zhuqi/upgrade_test/submit/src/../tests/hive/stress/2.1.1_to_2.3.7/stressTest/persistent/data/n1log:/hadoop/logs/
            - /home/zhuqi/upgrade_test/submit/src/../tests/hive/stress/2.1.1_to_2.3.7/stressTest/persistent/data/n1consolelog:/var/log/supervisor
        environment:
            SERVICE_PRECONDITION: '252.18.1.2:9870,252.18.1.2:9000'
        env_file:
            - ./hive.env
        expose:
            - 9000
            - 9870
            - 50010
            - 50020
            - 50070
            - 50075
            - 50090
            - 19888
            - 8188
            - 8020
            - 8030
            - 8031
            - 8032
            - 8033
            - 8040
            - 8042
            - 8088
            - 22
        
        
    DC3N2:
        container_name: container_hive_2.3.7_stressTest_N1
        image: image_hive_2.3.7
        command: bash -c 'sleep 0 && /usr/bin/supervisord'
        networks:
            network_2.1.1_to_2.3.7_stressTest_dc1ring:
                ipv4_address:  252.18.1.3
        volumes:
            - /home/zhuqi/upgrade_test/submit/src/../tests/hive/stress/2.1.1_to_2.3.7/stressTest/persistent/data/n2data:/hive/data
            - /home/zhuqi/upgrade_test/submit/src/../tests/hive/stress/2.1.1_to_2.3.7/stressTest/persistent/data/n2tmp:/tmp
            - /home/zhuqi/upgrade_test/submit/src/../tests/hive/stress/2.1.1_to_2.3.7/stressTest/persistent/data/n2log:/hive/logs/
            - /home/zhuqi/upgrade_test/submit/src/../tests/hive/stress/2.1.1_to_2.3.7/stressTest/persistent/data/n2consolelog:/var/log/supervisor
        environment:
            SERVICE_PRECONDITION: '252.18.1.2:9870,252.18.1.2:9000'
        env_file:
            - ./hive.env
        depends_on:
                - DC3N1
        expose:
            - 9083
            - 9000
            - 9870
            - 50010
            - 50020
            - 50070
            - 50075
            - 50090
            - 19888
            - 8188
            - 8020
            - 8030
            - 8031
            - 8032
            - 8033
            - 8040
            - 8042
            - 8088
            - 22        
        
networks:
    network_2.1.1_to_2.3.7_stressTest_dc1ring:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 252.18.1.1/24
        
